#Task 1: List Customers and Their Orders Display: Customer ID, Customer name, Order ID, Order date, Order status, Payment method 
Use JOIN Include customers who have no orders (if any).
SELECT c.customer_id, c.customer_name, o.order_id, o.order_date, o.order_status, o.payment_method
FROM Customers c
LEFT JOIN Orders o
ON c.customer_id = o.customer_id

#Task 2: Calculate Order Value Calculate the total value of each order. Display: Order ID, Total quantity, Order value
Formula: Order Value = quantity × unit_price
Requirements: Use SUM() Use GROUP BY. Round the order value to 2 decimal places.
Method 1:
SELECT distinct order_id, SUM(quantity) OVER(PARTITION BY order_id) AS total_quantity, SUM(quantity * unit_price) OVER(PARTITION BY order_id) AS order_value
FROM order_items
Method 2:
SELECT order_id, SUM(quantity) AS total_quantity, SUM(quantity * unit_price) AS order_value
FROM order_items
GROUP BY order_id

#Task 3: Calculate the total revenue generated by ShopSphere. Display: Total revenue
Requirements: Join ORDERS and ORDER_ITEMS. Consider only orders with status Completed. Use SUM(quantity * unit_price).
Business concept: Revenue should be calculated according to the defined order-status rule.
SELECT SUM(oi.quantity * oi.unit_price) AS total_revenue
FROM order_items oi
JOIN orders o
ON o.order_id = oi.order_id
WHERE o.order_status = 'Completed'

#Task 4: Quantity Sold and Sales by Product Display: Product ID, Product name, Total quantity sold, Total sales
Requirements: Join PRODUCTS, ORDER_ITEMS, and ORDERS. Consider only Completed orders. Use SUM() and GROUP BY. Sort by total sales descending.
Method 1:
SELECT distinct p.product_id, p.product_name, SUM(oi.quantity) OVER(PARTITION BY p.product_id) AS total_quantity_sold, oi.unit_price,
SUM(oi.unit_price * oi.quantity) OVER(PARTITION BY p.product_id) AS total_sales
FROM order_items oi
JOIN products p
ON p.product_id = oi.product_id
JOIN orders o
ON o.order_id = oi.order_id
WHERE o.order_status = 'Completed'
ORDER BY total_sales DESC
Method 2:
SELECT distinct p.product_id, p.product_name, SUM(oi.quantity) AS total_quantity_sold,
SUM(oi.unit_price * oi.quantity) AS total_sales
FROM order_items oi
JOIN products p
ON p.product_id = oi.product_id
JOIN orders o
ON o.order_id = oi.order_id
WHERE o.order_status = 'Completed'
GROUP BY p.product_id,p.product_name
ORDER BY total_sales DESC

#Task 5: Sales by Category Display: Category ID, Category name, Total quantity sold, Total sales
Requirements: Join all relevant tables. Include only Completed orders. Use aggregation and GROUP BY. Sort by total sales descending.
SELECT c.category_id, c.category_name, SUM(oi.quantity) AS total_quantity_sold, SUM(oi.quantity * oi.unit_price) AS total_sales
FROM categories c
JOIN products p
ON p.category_id = c.category_id
JOIN order_items oi
ON oi.product_id = p.product_id
JOIN orders o
ON o.order_id = oi.order_id
WHERE o.order_status = 'Completed'
GROUP BY c.category_id, c.category_name
ORDER BY total_sales DESC

#Task 6: Sales by Customer Display: Customer ID, Customer name, Total orders, Total quantity purchased, Total spending
Requirements: Include only Completed orders. Use COUNT(DISTINCT order_id). Use SUM(quantity * unit_price). Sort by total spending descending.
SELECT c.customer_id, c.customer_name, COUNT(DISTINCT o.order_id) AS total_orders, SUM(oi.quantity) AS total_quantity_purchased, SUM(oi.quantity * oi.unit_price) AS total_spending
FROM customers c
JOIN orders o
ON o.customer_id = c.customer_id
JOIN order_items oi
ON oi.order_id = o.order_id
WHERE o.order_status = 'Completed'
GROUP BY c.customer_id, c.customer_name
ORDER BY total_spending DESC

#Task 7: Find Repeat Customers Find customers who have placed at least 2 orders. Display: Customer ID, Customer name, Number of orders
Requirements: Use GROUP BY. Use HAVING. Count distinct orders. Consider Completed orders only.
SELECT c.customer_id, c.customer_name, COUNT(DISTINCT o.order_id) AS total_orders
FROM customers c
JOIN orders o
ON o.customer_id = c.customer_id
WHERE o.order_status = 'Completed'
GROUP BY c.customer_id, c.customer_name
HAVING COUNT(DISTINCT o.order_id) >= 2

#Task 8: Products Never Ordered Find products that have never appeared in any order. Display: Product ID, Product name, Category ID
Requirements: Use LEFT JOIN or NOT EXISTS. Do not count products with zero quantity as ordered unless the order item exists. Return products with no matching order items.
SELECT p.product_id, p.product_name, p.category_id
FROM products p
LEFT JOIN order_items oi
ON oi.product_id = p.product_id
WHERE oi.product_id IS NULL

#Task 9: Compare Order Totals by Status Calculate total order value for each order status. Display: Order status, Number of orders, Total order value
Requirements: Include all statuses: Completed, Shipped, Pending, and Cancelled. Use GROUP BY. Calculate order value using quantity × unit_price. Sort by total order value descending.
SELECT o.order_status, COUNT(DISTINCT o.order_id) AS total_orders, SUM(oi.quantity * oi.unit_price) AS total_order_value
FROM orders o
JOIN order_items oi
ON oi.order_id = o.order_id
GROUP BY o.order_status
ORDER BY total_order_value DESC

#Task 10: Business Summary Challenge Create a single query that displays: Total completed orders, Total completed quantity sold, Total completed revenue, Average completed order value
Requirements: Use joins and aggregation. Use CASE if needed. Ensure the average is calculated per order, not per order item.
SELECT COUNT(DISTINCT o.order_id) AS total_completed_orders, SUM(oi.quantity) AS total_completed_quantity_sold, SUM(oi.quantity * oi.unit_price) AS total_completed_revenue,
SUM(oi.quantity * oi.unit_price) / COUNT(DISTINCT o.order_id) AS average_completed_total_value
FROM orders o
JOIN order_items oi
ON oi.order_id = o.order_id
WHERE o.order_status = 'Completed'

